// <auto-generated />
using System;
using ClientAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientAPI.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20250407113141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientAPI.Models.ClientModel", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIDNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = new Guid("a1f1c1b1-d1e1-4f11-b1c1-001100110011"),
                            ClientAddress = "123 Main Road",
                            ClientCity = "Cape Town",
                            ClientEmailAddress = "ayanda.mokoena@example.com",
                            ClientFirstName = "Ayanda",
                            ClientGender = "Female",
                            ClientIDNumber = "9001014800087",
                            ClientLastName = "Mokoena",
                            ClientPhoneNumber = "0821234567"
                        },
                        new
                        {
                            ClientId = new Guid("a2f2c2b2-d2e2-4f22-b2c2-002200220022"),
                            ClientAddress = "45 Long Street",
                            ClientCity = "Cape Town",
                            ClientEmailAddress = "thabo.nkosi@example.com",
                            ClientFirstName = "Thabo",
                            ClientGender = "Male",
                            ClientIDNumber = "8802035800089",
                            ClientLastName = "Nkosi",
                            ClientPhoneNumber = "0732345678"
                        },
                        new
                        {
                            ClientId = new Guid("a3f3c3b3-d3e3-4f33-b3c3-003300330033"),
                            ClientAddress = "89 Victoria Road",
                            ClientCity = "Cape Town",
                            ClientEmailAddress = "naledi.dlamini@example.com",
                            ClientFirstName = "Naledi",
                            ClientGender = "Female",
                            ClientIDNumber = "9503214800081",
                            ClientLastName = "Dlamini",
                            ClientPhoneNumber = "0613456789"
                        },
                        new
                        {
                            ClientId = new Guid("a4f4c4b4-d4e4-4f44-b4c4-004400440044"),
                            ClientAddress = "22 Nelson Street",
                            ClientCity = "Cape Town",
                            ClientEmailAddress = "sibusiso.zulu@example.com",
                            ClientFirstName = "Sibusiso",
                            ClientGender = "Male",
                            ClientIDNumber = "9205145800084",
                            ClientLastName = "Zulu",
                            ClientPhoneNumber = "0744567890"
                        },
                        new
                        {
                            ClientId = new Guid("a5f5c5b5-d5e5-4f55-b5c5-005500550055"),
                            ClientAddress = "55 Beach Road",
                            ClientCity = "Cape Town",
                            ClientEmailAddress = "zanele.khumalo@example.com",
                            ClientFirstName = "Zanele",
                            ClientGender = "Female",
                            ClientIDNumber = "8707084800086",
                            ClientLastName = "Khumalo",
                            ClientPhoneNumber = "0835678901"
                        },
                        new
                        {
                            ClientId = new Guid("a6f6c6b6-d6e6-4f66-b6c6-006600660066"),
                            ClientAddress = "14 Mountain View",
                            ClientCity = "Cape Town",
                            ClientEmailAddress = "mandla.mbatha@example.com",
                            ClientFirstName = "Mandla",
                            ClientGender = "Male",
                            ClientIDNumber = "9109025800080",
                            ClientLastName = "Mbatha",
                            ClientPhoneNumber = "0726789012"
                        },
                        new
                        {
                            ClientId = new Guid("a7f7c7b7-d7e7-4f77-b7c7-007700770077"),
                            ClientAddress = "67 Rose Street",
                            ClientCity = "Cape Town",
                            ClientEmailAddress = "lerato.pule@example.com",
                            ClientFirstName = "Lerato",
                            ClientGender = "Female",
                            ClientIDNumber = "9601044800083",
                            ClientLastName = "Pule",
                            ClientPhoneNumber = "0617890123"
                        },
                        new
                        {
                            ClientId = new Guid("a8f8c8b8-d8e8-4f88-b8c8-008800880088"),
                            ClientAddress = "90 Hilltop Drive",
                            ClientCity = "Cape Town",
                            ClientEmailAddress = "sipho.ngcobo@example.com",
                            ClientFirstName = "Sipho",
                            ClientGender = "Male",
                            ClientIDNumber = "9303025800085",
                            ClientLastName = "Ngcobo",
                            ClientPhoneNumber = "0848901234"
                        },
                        new
                        {
                            ClientId = new Guid("a9f9c9b9-d9e9-4f99-b9c9-009900990099"),
                            ClientAddress = "101 Sunset Avenue",
                            ClientCity = "Cape Town",
                            ClientEmailAddress = "boitumelo.mahlangu@example.com",
                            ClientFirstName = "Boitumelo",
                            ClientGender = "Female",
                            ClientIDNumber = "9406154800088",
                            ClientLastName = "Mahlangu",
                            ClientPhoneNumber = "0609012345"
                        },
                        new
                        {
                            ClientId = new Guid("aa00c0b0-d0e0-4f00-b0c0-000000000000"),
                            ClientAddress = "33 Palm Street",
                            ClientCity = "Cape Town",
                            ClientEmailAddress = "kagiso.radebe@example.com",
                            ClientFirstName = "Kagiso",
                            ClientGender = "Male",
                            ClientIDNumber = "8911205800082",
                            ClientLastName = "Radebe",
                            ClientPhoneNumber = "0710123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
